### ISSUE TITLE
LTR run_ltrharvest.nestedloop.sh

### ISSUE THREAD

**Issue by Kapeel** [mcstitzer/maize_v4_TE_annotation#7]
I had to remove the space on line 28 and 77 "LTR_retrotransposon	" to "LTR_retrotransposon". I then ran sh run_ltrharvest.nestedloop.sh but the stdout throws this error/warning multiple times
```
Traceback (most recent call last):
  File "convert_ltrharvest_seq_gff_to_contignames.py", line 25, in <module>
    contigname=contig[seq.index(fields[0])]
IndexError: list index out of range
```
But it looks like the output files are created and have some content in them

**Comment by mcstitzer** [comment]
The space is not actually a space, but is a tab character. It's necessary for this to be a tab to get a gff3 file with just one copy of the TSD and the TE itself for the next subtracted round of searching (`${GENOMEBASE}.ltrharvest.contignames.tsd.ltrretrotransposon.gff3` and several `subtract${OLDINDEX}/${GENOME}.ltrharvest.contignames.tsd.ltrretrotransposon.gff3`'s) are generated, which should, for each LTR retrotransposon identified, have a target_site_duplication entry and a LTR_retrotransposon entry. 

```
1       LTRharvest      target_site_duplication 231813  231817  .       ?       .       Parent=repeat_region8
1       LTRharvest      LTR_retrotransposon     231818  241455  .       ?       .       ID=LTR_retrotransposon8;Parent=repeat_region8;ltr_similarity=96.08;seq_number=0
1       LTRharvest      target_site_duplication 243765  243769  .       ?       .       Parent=repeat_region9
1       LTRharvest      LTR_retrotransposon     243770  251243  .       ?       .       ID=LTR_retrotransposon9;Parent=repeat_region9;ltr_similarity=99.57;seq_number=0
```

I believe the error that was output was due to discrepancies in contig naming (see #2 ).
